/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import java.util.Random;
import javax.swing.JPanel;
import Model.User;

public class AcceptCard extends javax.swing.JPanel {

    DefaultComboBoxModel modelComboBox;
    Date currentDate = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    public String currentDateS = sdf.format(currentDate);
    SimpleDateFormat sdfy = new SimpleDateFormat("yyyy");
    public String currentDatey = sdfy.format(currentDate);
    public String ExperiedDate;

    /**
     * Creates new form AcceptCard
     */
    public AcceptCard() {
        initComponents();
        initComboBox();

        NewInfoCardPanel.setVisible(false);
        jTextField1.setEnabled(true);
        Money.setEnabled(false);

        handleDate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        Money = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        NewInfoCardPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NewBorrowerID = new javax.swing.JLabel();
        ActiveCode = new javax.swing.JLabel();
        ExpiriedDate = new javax.swing.JLabel();
        NewActiveCode = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Học sinh");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Người mượn");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("MSSV");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        Money.setText("Số tiền đặt cọc");
        Money.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MoneyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MoneyFocusLost(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ngày đăng kí :");

        jLabel2.setText("Ngày hết hạn :");

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Kì học :");

        jButton1.setText("Cấp thẻ mượn");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        NewInfoCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Thông tin thẻ mới ");

        jLabel5.setText("Mã người mượn :");

        jLabel7.setText("Ngày hết hạn :");

        NewBorrowerID.setText("jLabel8");

        ActiveCode.setText("jLabel8");

        ExpiriedDate.setText("jLabel8");

        NewActiveCode.setText("Mã kích hoạt :");

        javax.swing.GroupLayout NewInfoCardPanelLayout = new javax.swing.GroupLayout(NewInfoCardPanel);
        NewInfoCardPanel.setLayout(NewInfoCardPanelLayout);
        NewInfoCardPanelLayout.setHorizontalGroup(
            NewInfoCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewInfoCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewInfoCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(NewInfoCardPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(NewBorrowerID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewInfoCardPanelLayout.createSequentialGroup()
                        .addGroup(NewInfoCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewActiveCode))
                        .addGap(18, 18, 18)
                        .addGroup(NewInfoCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExpiriedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ActiveCode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NewInfoCardPanelLayout.setVerticalGroup(
            NewInfoCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewInfoCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(NewInfoCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NewBorrowerID))
                .addGap(18, 18, 18)
                .addGroup(NewInfoCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActiveCode)
                    .addComponent(NewActiveCode))
                .addGap(18, 18, 18)
                .addGroup(NewInfoCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ExpiriedDate))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jRadioButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Money, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(jTextField3)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(21, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewInfoCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(NewInfoCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {
            jTextField1.setEnabled(false);
            Money.setEnabled(true);

        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if (jTextField1.getText().equals("MSSV")) {
            jTextField1.setText("");
            jTextField1.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setForeground(Color.gray);
            jTextField1.setText("MSSV");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void MoneyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MoneyFocusGained
        if (Money.getText().equals("Số tiền đặt cọc")) {
            Money.setText("");
            Money.setForeground(Color.black);
        }
    }//GEN-LAST:event_MoneyFocusGained

    private void MoneyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MoneyFocusLost
        if (Money.getText().isEmpty()) {
            Money.setForeground(Color.gray);
            Money.setText("Số tiền đặt cọc");
        }
    }//GEN-LAST:event_MoneyFocusLost

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        if (jTextField3.getText().equals(currentDateS)) {
            jTextField3.setText("");
            jTextField3.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        if (jTextField3.getText().isEmpty()) {
            jTextField3.setForeground(Color.gray);
            jTextField3.setText(currentDateS);
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
            jTextField1.setEnabled(true);
            jComboBox1.setEnabled(true);
            Money.setEnabled(false);

        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        if (jTextField4.getText().equals(ExperiedDate)) {
            jTextField4.setText("");
            jTextField4.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        if (jTextField4.getText().isEmpty()) {
            jTextField4.setForeground(Color.gray);
            jTextField4.setText(ExperiedDate);
        }
    }//GEN-LAST:event_jTextField4FocusLost

    /**
     * xử lý nhận các trường thông tin nhập vào,và tạo thẻ mới và người dùng mới
     *
     * @param evt
     */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        try {
            if (jRadioButton1.isSelected()) {
                CreateNewCardFrame.newnguoimuon.setborrower_Student_ID(jTextField1.getText());
                CreateNewCardFrame.newnguoimuon.setborrower_Deposit(0);
            } else {
                CreateNewCardFrame.newnguoimuon.setborrower_Student_ID(null);
                CreateNewCardFrame.newnguoimuon.setborrower_Deposit(Integer.valueOf(Money.getText()));
            }
            CreateNewCardFrame.newnguoimuon.setborrower_Study_Period(getStudyPeriod(jComboBox1.getSelectedItem().toString()));
            System.out.println(getStudyPeriod(jComboBox1.getSelectedItem().toString())+"asdjasdhkjsadhaks");
            CreateNewCardFrame.newnguoimuon.setuser_Username(CreateNewCardFrame.taikhoan.getuser_Username());
            CreateNewCardFrame.newthemuon.setborrowingcard_Expried_Date(jTextField4.getText());
            Random r = new Random();
            int a = r.nextInt(999999);

            CreateNewCardFrame.newthemuon.setborrowingcard_Actived_Code(String.valueOf(a));
            String b = new Create_BorrowingCard_Controller().registerborrower(CreateNewCardFrame.newnguoimuon, CreateNewCardFrame.newthemuon, CreateNewCardFrame.taikhoan);
            CreateNewCardFrame.newthemuon.setborrowingcard_Borrower_ID(b);

            UpdateCreateCardUI();//update lại giao diện khi tạo thẻ mới thành công

        } catch (SQLException ex) {
            Logger.getLogger(AcceptCard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AcceptCard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * Hiển thị mã kích hoạt thẻ và thông tin cơ bản của thẻ
     */
    public void UpdateCreateCardUI() {
        NewInfoCardPanel.setVisible(true);
        NewBorrowerID.setText(CreateNewCardFrame.newthemuon.getborrowingcard_ID());
        ActiveCode.setText(CreateNewCardFrame.newthemuon.getborrowingcard_Actived_Code());
        ExpiriedDate.setText(CreateNewCardFrame.newthemuon.getborrowingcard_Expried_Date());
        CreateNewCardFrame.taikhoan = new User();
        CreateNewCardFrame.ici.getAccountInfoUi().setInfo();
        CreateNewCardFrame.ici.getAccountInfoUi().getLbGender().setText("");
        CreateNewCardFrame.getSearchAccountPanel().jTextField1.setText("Search");

    }

    /**
     * Khởi tạo dữ liệu các kì học cho comboBox
     */
    private void initComboBox() {
        String[] dataComboBox = {"2017-1", "2017-2", "2017-3", "2018-1", "2018-2", "2018-3", "2019-1", "2019-2", "2019-3",
            "2020-1", "2020-2", "2020-3", "2021-1", "2021-2", "2021-3", "2022-1", "2022-2", "2022-3"};
        modelComboBox = (DefaultComboBoxModel) jComboBox1.getModel();
        modelComboBox.removeAllElements();
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(dataComboBox));
    }

    private String getStudyPeriod(String studyPeriod) {
        String result="";
        switch (studyPeriod) {
            case "2017-1":
                result = "15/01/2017";break;
            case "2017-2":
                result = "30/06/2017";break;
            case "2017-3":
                result = "01/09/2017";break;
            case "2018-1":
                result = "15/01/2018";break;
            case "2018-2":
                result = "30/06/2018";break;
            case "2018-3":
                result = "01/09/2018";break;
            case "2019-1":
                result = "15/01/2019";break;
            case "2019-2":
                result = "30/06/2019";break;
            case "2019-3":
                result = "01/09/2019";break;
            case "2020-1":
                result = "15/01/2020";break;
            case "2020-2":
                result = "30/06/2020";break;
            case "2020-3":
                result = "01/09/2020";break;
            case "2021-1":
                result = "15/01/2021";break;
            case "2021-2":
                result = "30/06/2021";break;
            case "2021-3":
                result = "01/09/2021";break;
            case "2022-1":
                result = "15/01/2022";break;
            case "2022-2":
                result = "30/06/2022";break;
            case "2022-3":
                result = "01/09/2022";break;

        }
        return result;
    }

    public JPanel getNewInfoPanel() {
        return NewInfoCardPanel;
    }

    private void handleDate() {
        int incrCurrentDate = (currentDate.getMonth() + 18) / 12;
        int currentMonth = currentDate.getMonth() % 12;
        int currentYear = Integer.valueOf(currentDatey) + incrCurrentDate;
        ExperiedDate = currentDate.getDate() + "/" + currentMonth + "/" + currentYear;

        jTextField3.setText(currentDateS);
        jTextField3.setForeground(Color.gray);
        jTextField4.setText(ExperiedDate);
        jTextField4.setForeground(Color.gray);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActiveCode;
    private javax.swing.JLabel ExpiriedDate;
    private javax.swing.JTextField Money;
    private javax.swing.JLabel NewActiveCode;
    private javax.swing.JLabel NewBorrowerID;
    private javax.swing.JPanel NewInfoCardPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
