/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import java.awt.GridLayout;

public class CreateNewCardFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreateNewCardFrame
     */
    public static InputCardInfo ici = new InputCardInfo();
    public static User taikhoan = new User();
    public static Borrower newnguoimuon = new Borrower();
    public static BorrowingCard newthemuon = new BorrowingCard();
    public static SearchAccountPanel sap = new SearchAccountPanel();

    public CreateNewCardFrame() {
        initComponents();
        
         setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         setLocationRelativeTo(this);
        sap.setSize(800, 80);
        ici.setSize(800, 500);
        this.setLayout(null);
        sap.setBounds(0, 0, 800, 80);
        ici.setBounds(0, 80, 800, 600);
        this.add(sap);
        this.add(ici);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tạo thẻ mới");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static SearchAccountPanel getSearchAccountPanel(){
        return sap;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
