/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.GridLayout;

public class InputCardInfo extends javax.swing.JPanel {

    /**
     * Creates new form InputCardInfo
     */
    public static AccountInfo ai = new AccountInfo();
    public static AcceptCard ac= new AcceptCard();
    
    public InputCardInfo() {
        initComponents();
        this.setLayout(null);
        ai.setBounds(0,0,381, 500);
        ac.setBounds(381,0,430,500);
        this.add(ai);
        this.add(ac);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
     public AccountInfo getAccountInfoUi(){
         return ai;
     }
     public AcceptCard getAcceptCardUi(){
         return ac;
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
