/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BorrowingCard_Controller;
import Model.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class SearchBorrowCardForm extends javax.swing.JPanel {

    BorrowingCard_Controller cardController;
    /**
     * Creates new form TimKiemTheForm
     */
    public SearchBorrowCardForm() {
        initComponents();
        cardController = new BorrowingCard_Controller();
        try {
            putIntoTable(cardController.getAllCard(), tableCardInformation);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchBorrowCardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTypeCardInformation = new javax.swing.JLabel();
        tfInformation = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCardInformation = new javax.swing.JTable();

        lbTypeCardInformation.setText("Thông tin tìm kiếm");

        tfInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInformationActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tableCardInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tableCardInformation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTypeCardInformation)
                        .addGap(18, 18, 18)
                        .addComponent(tfInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSearch)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTypeCardInformation)
                    .addComponent(tfInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInformationActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            // TODO add your handling code here:
            putIntoTable(cardController.getCardSearchingList(tfInformation.getText()), tableCardInformation);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchBorrowCardForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSearchActionPerformed
/** Hàm này đẩy thông tin của tất cả các thẻ từ CSDL vào bàng hiển thị
 * 
 * @param theMuon là danh sách tất cả các thẻ trong CSDL
 * @param table là bảng để hiển thị dữ liệu
 *
 **/
    public void putIntoTable(ArrayList<BorrowingCard> theMuon, JTable table) {    // cần đẩy thêm tên tài khoản và thông tin liên hệ
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Ma the");
        model.addColumn("Ten tai khoan");
        model.addColumn("Ten day du");
        model.addColumn("Email");
        model.addColumn("Gioi tinh");
        model.addColumn("Lien He");
        model.addColumn("Mssv");
        model.addColumn("Ki hoc");

        for (int i = 0; i < theMuon.size(); i++) {
            Vector vec = new Vector();
            vec.add(theMuon.get(i).getborrowingcard_Borrower_ID());
            vec.add(theMuon.get(i).getborrowingcard_Borrower().getuser_Username());
            vec.add(theMuon.get(i).getborrowingcard_Borrower().getuser_Name());
            vec.add(theMuon.get(i).getborrowingcard_Borrower().getuser_Email());
            if (theMuon.get(i).getborrowingcard_Borrower().getborrower_Deposit() == 0) {
                vec.add("Nam");
            } else {
                vec.add("Nu");
            }
            vec.add(null);
            vec.add(theMuon.get(i).getborrowingcard_Borrower().getborrower_Student_ID());
            vec.add(theMuon.get(i).getborrowingcard_Borrower().getborrower_Study_Period());
            model.addRow(vec);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTypeCardInformation;
    private javax.swing.JTable tableCardInformation;
    private javax.swing.JTextField tfInformation;
    // End of variables declaration//GEN-END:variables
}
