/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ReturnBook_Controller;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class tableBookInfoBorrow extends javax.swing.JPanel {

    public static DefaultTableModel model;

    /**
     * Creates new form tableBookInfoBorrow
     */
    public tableBookInfoBorrow() {
        initComponents();
        updateTable();
        model = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sách", "Ngày mượn", "Hạn trả", "trạng thái", "Lý do phạt", "Tiền phạt", "Trả sách"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jButton1.setText("Trả sách");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Trả những cuốn sách đã chọn vào cơ sở dữ liệu
     *
     * @param evt
     */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (!ReturnBookFrame.dataTable.isEmpty()) {
            try {
                boolean[] id = new boolean[ReturnBookFrame.dataTable.size()];
                for (int i = 0; i < ReturnBookFrame.dataTable.size(); i++) {
                    id[i] = Boolean.valueOf(model.getValueAt(i, 6).toString());
                    ReturnBookFrame.dataTable.get(i)[6] = String.valueOf(model.getValueAt(i, 4).toString());
                    ReturnBookFrame.dataTable.get(i)[7] = String.valueOf(model.getValueAt(i, 5).toString());
                }
                new ReturnBook_Controller().ReturnBook(ReturnBookFrame.dataTable, id);
                new ReturnBook_Controller().UpdateInfoBorrowTable(ReturnBookFrame.IdInfoBorrow);

                ReturnBookFrame.siP.getSearchBorrowerP().SearchBookIsBorrowed();
                updateTable();
            } catch (SQLException ex) {
                Logger.getLogger(tableBookInfoBorrow.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(tableBookInfoBorrow.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(tableBookInfoBorrow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton1MouseClicked

    public static JTable getTable() {
        return jTable1;
    }

    /**
     * Cập nhật lại bảng những cuốn sách còn mượn sau khi trả sách
     */
    public void updateTable() {
        if (!ReturnBookFrame.dataTable.isEmpty()) {
            model.setRowCount(0);
        }
        for (int i = 0; i < ReturnBookFrame.dataTable.size(); i++) {
            Object[] newRow = {
                ReturnBookFrame.dataTable.get(i)[2],
                ReturnBookFrame.dataTable.get(i)[3],
                ReturnBookFrame.dataTable.get(i)[4],
                ReturnBookFrame.dataTable.get(i)[5],
                ReturnBookFrame.dataTable.get(i)[6],
                ReturnBookFrame.dataTable.get(i)[7],
                ReturnBookFrame.dataTable.get(i)[8],};
            model.addRow(newRow);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
